export { aliases, shorthands, affordances, cmdList, plumbing,types };

// short names for common things
var shorthands = {
    'un': 'uninstall',
    'rb': 'rebuild',
    'list': 'ls',
    'ln': 'link',
    'create': 'init',
    'i': 'install',
    'it': 'install-test',
    'cit': 'install-ci-test',
    'up': 'update',
    'c': 'config',
    's': 'search',
    'se': 'search',
    'unstar': 'star', // same function
    'tst': 'test',
    't': 'test',
    'ddp': 'dedupe',
    'v': 'view',
    'run': 'run-script',
    'clean-install': 'ci',
    'clean-install-test': 'cit'
}

var affordances = {
    'la': 'ls',
    'll': 'ls',
    'verison': 'version',
    'ic': 'ci',
    'innit': 'init',
    'isntall': 'install',
    'install-clean': 'ci',
    'isntall-clean': 'ci',
    'dist-tags': 'dist-tag',
    'apihelp': 'help',
    'find-dupes': 'dedupe',
    'upgrade': 'update',
    'udpate': 'update',
    'login': 'adduser',
    'add-user': 'adduser',
    'author': 'owner',
    'home': 'docs',
    'issues': 'bugs',
    'info': 'view',
    'show': 'view',
    'find': 'search',
    'add': 'install',
    'unlink': 'uninstall',
    'remove': 'uninstall',
    'rm': 'uninstall',
    'r': 'uninstall',
    'rum': 'run-script',
    'sit': 'cit'
}

// these are filenames in .
var cmdList = [
    'user',
    'category',
    'ci',
    'install-ci-test',
    'install',
    'install-test',
    'uninstall',
    'cache',
    'config',
    'set',
    'get',
    'update',
    'outdated',
    'prune',
    'pack',
    'dedupe',
    'hook',

    'rebuild',
    'link',

    'publish',
    'star',
    'stars',
    'adduser',
    'login', // This is an alias for `adduser` but it can be confusing
    'logout',
    'unpublish',
    'owner',
    'access',
    'team',
    'deprecate',
    'shrinkwrap',
    'token',
    'profile',
    'audit',

    'help',
    'help-search',
    'ls',
    'search',
    'view',
    'init',
    'version',
    'edit',
    'explore',
    'docs',
    'repo',
    'bugs',
    'root',
    'prefix',
    'bin',
    'whoami',
    'dist-tag',
    'ping',

    'test',
    'stop',
    'start',
    'restart',
    'run-script',
    'completion',
    'doctor'
]

var plumbing = [
    'build',
    'unbuild',
    'xmas',
    'substack',
    'visnup'
]

var aliases = Object.assign({}, shorthands, affordances);

var types = {
    access: [null, 'restricted', 'public'],
    'allow-same-version': Boolean,
    'always-auth': Boolean,
    also: [null, 'dev', 'development'],
    audit: Boolean,
    'audit-level': ['low', 'moderate', 'high', 'critical'],
    'auth-type': ['legacy', 'sso', 'saml', 'oauth'],
    'bin-links': Boolean,
    browser: [null, String],
    ca: [null, String, Array],
    'cache-lock-stale': Number,
    'cache-lock-retries': Number,
    'cache-lock-wait': Number,
    'cache-max': Number,
    'cache-min': Number,
    cert: [null, String],
    cidr: [null, String, Array],
    color: ['always', Boolean],
    depth: Number,
    description: Boolean,
    dev: Boolean,
    'dry-run': Boolean,
    editor: String,
    'engine-strict': Boolean,
    force: Boolean,
    'fetch-retries': Number,
    'fetch-retry-factor': Number,
    'fetch-retry-mintimeout': Number,
    'fetch-retry-maxtimeout': Number,
    git: String,
    'git-tag-version': Boolean,
    'commit-hooks': Boolean,
    global: Boolean,
    'global-style': Boolean,
    group: [Number, String],
    'user-agent': String,
    'ham-it-up': Boolean,
    'heading': String,
    'if-present': Boolean,
    'ignore-prepublish': Boolean,
    'ignore-scripts': Boolean,
    'init-author-name': String,
    'init-author-email': String,
    'init-license': String,
    json: Boolean,
    key: [null, String],
    'legacy-bundling': Boolean,
    link: Boolean,
    loglevel: ['silent', 'error', 'warn', 'notice', 'http', 'timing', 'info', 'verbose', 'silly'],
    'logs-max': Number,
    long: Boolean,
    maxsockets: Number,
    message: String,
    'metrics-registry': [null, String],
    'node-options': [null, String],
    'noproxy': [null, String, Array],
    offline: Boolean,
    'onload-script': [null, String],
    only: [null, 'dev', 'development', 'prod', 'production'],
    optional: Boolean,
    'package-lock': Boolean,
    otp: [null, String],
    'package-lock-only': Boolean,
    parseable: Boolean,
    'prefer-offline': Boolean,
    'prefer-online': Boolean,
    preid: String,
    production: Boolean,
    progress: Boolean,
    'read-only': Boolean,
    'rebuild-bundle': Boolean,
    rollback: Boolean,
    save: Boolean,
    'save-bundle': Boolean,
    'save-dev': Boolean,
    'save-exact': Boolean,
    'save-optional': Boolean,
    'save-prefix': String,
    'save-prod': Boolean,
    scope: String,
    'script-shell': [null, String],
    'scripts-prepend-node-path': [false, true, 'auto', 'warn-only'],
    searchopts: String,
    searchexclude: [null, String],
    searchlimit: Number,
    searchstaleness: Number,
    'send-metrics': Boolean,
    shell: String,
    shrinkwrap: Boolean,
    'sign-git-commit': Boolean,
    'sign-git-tag': Boolean,
    'sso-poll-frequency': Number,
    'sso-type': [null, 'oauth', 'saml'],
    'strict-ssl': Boolean,
    tag: String,
    timing: Boolean,
    unicode: Boolean,
    'unsafe-perm': Boolean,
    'update-notifier': Boolean,
    usage: Boolean,
    user: [Number, String],
    version: Boolean,
    'tag-version-prefix': String,
    versions: Boolean,
    viewer: String,
    _exit: Boolean
  }